inoremap jj <Esc>
inoremap ( ()<Esc>i
inoremap { {}<Esc>i
inoremap [ []<Esc>i
inoremap " ""<Esc>i
inoremap ' ''<Esc>i
inoremap ` ``<Esc>i
inoremap < <><Esc>i
noremap ew <C-w><C-w>
noremap <leader>; A;<Esc>
noremap <leader>e :Lexplore<CR>
noremap <leader>w :w<CR>
noremap <leader>wq :wq<CR>
noremap <leader>q :q<CR>
noremap <leader>qq :q!<CR>
noremap <leader>re :so<Space>%<CR>
